self:
  host: localhost
  public_port: 8080
  private_port: 8081
  language: zh_cn
dependency:
  authorization_endpoint: http://authorization-private.svc.cluster.local:4445
  user_management_endpoint: http://user-management-private.svc.cluster.local:30980
